
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const ReportEngine = {
    /**
     * Generates a printable PDF Gate Pass for Export
     */
    generateGatePassPDF: (passData: any) => {
        const doc = new jsPDF();

        // Header
        doc.setFontSize(22);
        doc.setTextColor(40);
        doc.text("DELIVERY HUB PRO", 105, 20, { align: "center" });

        doc.setFontSize(16);
        doc.text("EXPORT GATE PASS", 105, 30, { align: "center" });

        doc.setLineWidth(0.5);
        doc.line(20, 35, 190, 35);

        // Pass Details
        doc.setFontSize(12);
        doc.setTextColor(0);

        let y = 50;
        const lineHeight = 10;

        doc.setFont("helvetica", "bold");
        doc.text(`Pass Number:`, 20, y);
        doc.setFont("helvetica", "normal");
        doc.text(passData.pass_number || "N/A", 60, y);

        doc.setFont("helvetica", "bold");
        doc.text(`Date Issued:`, 120, y);
        doc.setFont("helvetica", "normal");
        doc.text(new Date().toLocaleDateString(), 150, y);

        y += lineHeight;

        doc.setFont("helvetica", "bold");
        doc.text(`GD Number:`, 20, y);
        doc.setFont("helvetica", "normal");
        doc.text(passData.gd_number || "N/A", 60, y);

        y += lineHeight + 5;

        // Vehicle Info Section
        doc.setFillColor(240, 240, 240);
        doc.rect(20, y, 170, 10, 'F');
        doc.setFont("helvetica", "bold");
        doc.text("VEHICLE & DRIVER DETAILS", 25, y + 7);
        y += 15;

        doc.text(`Vehicle No:`, 20, y);
        doc.setFont("helvetica", "normal");
        doc.text(passData.vehicle_number || "N/A", 60, y);

        y += lineHeight;

        doc.setFont("helvetica", "bold");
        doc.text(`Driver Name:`, 20, y);
        doc.setFont("helvetica", "normal");
        doc.text(passData.driver_name || "Unknown", 60, y);

        y += lineHeight;

        doc.setFont("helvetica", "bold");
        doc.text(`CNIC:`, 20, y);
        doc.setFont("helvetica", "normal");
        doc.text(passData.driver_cnic || "N/A", 60, y);

        y += lineHeight + 10;

        // Cargo Info
        doc.setFillColor(240, 240, 240);
        doc.rect(20, y, 170, 10, 'F');
        doc.setFont("helvetica", "bold");
        doc.text("CARGO", 25, y + 7);
        y += 15;

        doc.setFont("helvetica", "bold");
        doc.text(`No. of Packages:`, 20, y);
        doc.setFont("helvetica", "normal");
        doc.text(String(passData.no_of_packages || "0"), 60, y);

        // Footer / Signature
        y = 250;
        doc.line(20, y, 70, y);
        doc.text("Driver Signature", 20, y + 5);

        doc.line(140, y, 190, y);
        doc.text("Terminal Manager", 140, y + 5);

        // Disclaimer
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text("This pass is valid for 24 hours only. Generated by Delivery Hub Pro System.", 105, 280, { align: "center" });

        doc.save(`GatePass_${passData.pass_number}.pdf`);
    },

    /**
     * Generates a Commercial Invoice PDF
     */
    generateInvoicePDF: async (invoiceData: any) => {
        const doc = new jsPDF();

        // Add Logo
        try {
            const logoUrl = '/kohesar_logo.png';
            const img = new Image();
            img.src = logoUrl;
            await new Promise((resolve, reject) => {
                img.onload = resolve;
                img.onerror = resolve;
            });
            const logoWidth = 50;
            const logoHeight = (img.height * logoWidth) / img.width;
            doc.addImage(img, 'PNG', 14, 10, logoWidth, logoHeight);
        } catch (e) {
            console.warn("Logo load failed", e);
        }

        // Company Header
        doc.setFontSize(24);
        doc.setTextColor(0, 51, 102); // Navy Blue
        doc.text("INVOICE", 150, 30); // Lowered Y

        doc.setFontSize(14);
        doc.setTextColor(100);
        doc.text("Kohesar Logistics (PVT) LTD", 14, 45); // Below Logo
        doc.setFontSize(10);
        doc.text("Karachi, Pakistan", 14, 51);
        doc.text("info@kohesarlogistics.com", 14, 57);

        // Invoice Specifics
        let y = 70;
        doc.setTextColor(0);
        doc.setFont("helvetica", "bold");
        doc.text(`Bill To:`, 14, y);
        doc.setFont("helvetica", "normal");
        doc.text(invoiceData.customer_name || "Valued Customer", 14, y + 5);
        doc.text(invoiceData.company_address || "Karachi, Pakistan", 14, y + 10);

        doc.setFont("helvetica", "bold");
        doc.text(`Invoice #:`, 140, y);
        doc.text(`Date:`, 140, y + 6);
        doc.text(`Due Date:`, 140, y + 12);

        doc.setFont("helvetica", "normal");
        doc.text(invoiceData.invoice_number || "INV-001", 170, y);
        doc.text(invoiceData.date || new Date().toISOString().split('T')[0], 170, y + 6);
        doc.text(invoiceData.due_date || new Date().toISOString().split('T')[0], 170, y + 12);


        // Table
        y += 25;

        const items = invoiceData.items || [];
        const tableData = items.map((item: any) => [
            item.description || "Service Charge",
            item.quantity || 1,
            item.unit_price || 0,
            (item.quantity * item.unit_price).toFixed(2)
        ]);

        autoTable(doc, {
            startY: y,
            head: [['Description', 'Qty', 'Unit Price', 'Total']],
            body: tableData,
            foot: [['', '', 'Total', invoiceData.total_amount || 0]],
            theme: 'grid',
            headStyles: { fillColor: [0, 51, 102] },
            footStyles: { fillColor: [240, 240, 240], textColor: 0, fontStyle: 'bold' }
        });

        // Notes
        const finalY = (doc as any).lastAutoTable.finalY + 20;
        doc.setFontSize(10);
        doc.text("Payment Advice:", 20, finalY);
        doc.setTextColor(100);
        doc.text("Please make checks payable to Global Logistics Co.", 20, finalY + 6);
        doc.text("Bank Transfer: HBL - 1234 5678 9012 3456", 20, finalY + 12);

        doc.save(`Invoice_${invoiceData.invoice_number}.pdf`);
    }
};
